version: "2"
services:
    backend:
       image: medialab/hyphe_backend:latest
       restart: always
       links:
        - "mongo:mongo"
        - "crawler:crawler"
       environment:
        - HYPHE_MONGODB_HOST=mongo
        - HYPHE_MONGODB_PORT=27017
        - HYPHE_CRAWLER_HOST=crawler
        - HYPHE_CRAWLER_PORT=6800
    frontend:
       image: medialab/hyphe_frontend:latest
       restart: always
       environment:
        - HYPHE_API_URI=api
       links:
        - "backend:backend"
       ports:
        - "8000:80"
    crawler:
       image: medialab/hyphe_crawler:latest
       restart: always
       links:
        - "mongo:mongo"
       volumes:
        - ./config/scrapyd.config:/etc/scrapyd/conf.d/100-hyphe
    mongo:
       image: mongo:3.0
       restart: always
